[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"} 
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"} 
size = 15 

[window]
opacity = 0.5
blur = true
startup_mode = "Maximized"

[mouse]
hide_when_typing = true
